"""Turn the accumulated CSVs into what Hugo renders.

Runs with no credentials and no data — that is the point: the site must build
(showing "no data yet") before the first GA4 pull, so every /analytics/<slug>/
URL that a calcofi.io card links to resolves from day one.

Writes:
  content/products/<slug>.md   generated stub, one per registry product
  data/usage/<slug>.json       that product's numbers
  data/usage_summary.json      index-page totals + the comparison table
"""

from __future__ import annotations

import datetime as dt
import json
import sys

from common import CONTENT, DATA, USAGE, products, read_csv

STUB = """---
# GENERATED by scripts/build.py from data/registry.yml — do not hand-edit.
title: "{title}"
slug: "{slug}"
product: "{slug}"
url: "/{slug}/"
live_url: "{live_url}"
type: products
layout: product
---
"""


def num(v, default=0.0):
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def series(slug: str) -> list[dict]:
    """Daily rows for one product, oldest first."""
    return sorted(read_csv(DATA / "daily" / f"{slug}.csv"), key=lambda r: r["date"])


def window(rows: list[dict], days: int, offset: int = 0) -> list[dict]:
    end = dt.date.today() - dt.timedelta(days=offset)
    start = end - dt.timedelta(days=days)
    return [r for r in rows if start.isoformat() < r["date"] <= end.isoformat()]


def totals(rows: list[dict]) -> dict:
    """Sum the raw metrics, then derive. Never average an average."""
    t = {k: sum(num(r.get(k)) for r in rows) for k in
         ("activeUsers", "newUsers", "sessions", "engagedSessions",
          "screenPageViews", "eventCount", "userEngagementDuration")}
    # GA4's "average engagement time per active user"
    t["avgEngagementSeconds"] = round(t["userEngagementDuration"] / t["activeUsers"], 1) if t["activeUsers"] else 0
    t["engagedSessionRate"] = round(t["engagedSessions"] / t["sessions"], 3) if t["sessions"] else 0
    t["viewsPerUser"] = round(t["screenPageViews"] / t["activeUsers"], 2) if t["activeUsers"] else 0
    return {k: (round(v, 1) if isinstance(v, float) else v) for k, v in t.items()}


def delta(cur: float, prev: float):
    """Percent change, or None when there is no baseline to compare against."""
    if not prev:
        return None
    return round((cur - prev) / prev * 100, 1)


def rolling_mean(rows: list[dict], field: str, n: int = 7) -> list[float]:
    vals = [num(r.get(field)) for r in rows]
    out = []
    for i in range(len(vals)):
        w = vals[max(0, i - n + 1): i + 1]
        out.append(round(sum(w) / len(w), 2) if w else 0)
    return out


def build() -> dict:
    CONTENT.mkdir(parents=True, exist_ok=True)
    USAGE.mkdir(parents=True, exist_ok=True)

    prods = products()
    table, any_data = [], False

    for p in prods:
        slug = p["slug"]
        rows = series(slug)
        any_data = any_data or bool(rows)

        cur, prev = window(rows, 28), window(rows, 28, 28)
        t28, p28 = totals(cur), totals(prev)

        geo = sorted(read_csv(DATA / "geo" / f"{slug}.csv"),
                     key=lambda r: -num(r.get("activeUsers")))
        # GA4 returns one row per (country, region), so a country with regions
        # would otherwise appear several times in the map and the ranked bars
        by_country: dict[str, dict] = {}
        for g in geo:
            c = by_country.setdefault(g.get("countryId", "") or g.get("country", ""),
                                      {"country": g.get("country", ""),
                                       "countryId": g.get("countryId", ""),
                                       "activeUsers": 0.0})
            c["activeUsers"] += num(g.get("activeUsers"))
        geo_country = sorted(by_country.values(), key=lambda r: -r["activeUsers"])
        events = sorted(read_csv(DATA / "events" / f"{slug}.csv"),
                        key=lambda r: -num(r.get("eventCount")))[:12]

        doc = {
            "slug": slug,
            "title": p.get("title", slug),
            "live_url": p.get("live_url", ""),
            "property": p.get("property", ""),
            "has_data": bool(rows),
            "first_day": rows[0]["date"] if rows else "",
            "last_day": rows[-1]["date"] if rows else "",
            "totals_28d": t28,
            "delta_28d": {k: delta(t28.get(k, 0), p28.get(k, 0))
                          for k in ("activeUsers", "sessions", "engagedSessions",
                                    "avgEngagementSeconds", "screenPageViews")},
            "daily": [{"date": r["date"],
                       "activeUsers": num(r.get("activeUsers")),
                       "sessions": num(r.get("sessions"))} for r in rows],
            "daily_mean7": rolling_mean(rows, "activeUsers"),
            # country totals drive the map and the ranked bars; the per-region
            # detail stays available for the table twin
            "geo_country": geo_country,
            "geo": [{"country": g.get("country", ""), "countryId": g.get("countryId", ""),
                     "region": g.get("region", ""), "activeUsers": num(g.get("activeUsers"))}
                    for g in geo],
            "events": [{"name": e.get("eventName", ""), "count": num(e.get("eventCount")),
                        "users": num(e.get("activeUsers"))} for e in events],
        }

        # the query log exists for db-viz-hex alone
        if p.get("sheet_tab"):
            log_daily = read_csv(DATA / "hex_log" / "daily.csv")
            if log_daily:
                doc["log"] = {
                    "daily": log_daily,
                    "events": read_csv(DATA / "hex_log" / "events.csv"),
                    # ranked here, not in the template: the CSV is grouped by
                    # param name, so rendering it in file order puts a count of
                    # 2 above a count of 23 in the same bar chart
                    "params": sorted(read_csv(DATA / "hex_log" / "params.csv"),
                                     key=lambda r: -num(r.get("n"))),
                    "versions": read_csv(DATA / "hex_log" / "versions.csv"),
                }

        (USAGE / f"{slug}.json").write_text(json.dumps(doc, indent=1))
        (CONTENT / f"{slug}.md").write_text(STUB.format(
            title=p.get("title", slug), slug=slug, live_url=p.get("live_url", "")))

        table.append({
            "slug": slug, "title": p.get("title", slug),
            # engagedSessions leads: a crawler sweeping a docs site mints one
            # "active user" per page fetch (no cookie, so a fresh client id each
            # time) and engages with none of them, which put calcofi4db at the
            # top of this table on 219 users and 3.2% engagement. Engaged
            # sessions are the ones a person actually spent time in.
            "engagedSessions": t28.get("engagedSessions", 0),
            "activeUsers": t28.get("activeUsers", 0),
            "sessions": t28.get("sessions", 0),
            "engagementRate": t28.get("engagedSessionRate", 0),
            "avgEngagementSeconds": t28.get("avgEngagementSeconds", 0),
            "delta": doc["delta_28d"]["engagedSessions"],
            "spark": [d["activeUsers"] for d in doc["daily"][-90:]],
            # enough traffic to judge, and almost none of it engaged
            "mostly_automated": (t28.get("activeUsers", 0) >= 20
                                 and t28.get("engagedSessionRate", 0) < 0.10),
        })

    table.sort(key=lambda r: (-r["engagedSessions"], -r["activeUsers"]))
    summary = {
        # stamped so the footer can flag a cron that has silently stopped
        "generated": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "has_data": any_data,
        "n_products": len(prods),
        "totals_28d": {
            "engagedSessions": sum(r["engagedSessions"] for r in table),
            "activeUsers": sum(r["activeUsers"] for r in table),
            "sessions": sum(r["sessions"] for r in table),
        },
        "n_mostly_automated": sum(1 for r in table if r["mostly_automated"]),
        "products": table,
    }
    (USAGE.parent / "usage_summary.json").write_text(json.dumps(summary, indent=1))
    return summary


if __name__ == "__main__":
    s = build()
    print(f"built {s['n_products']} products; data present: {s['has_data']}; "
          f"28d active users: {s['totals_28d']['activeUsers']:.0f}", file=sys.stderr)
